### ISSUE TITLE
后台地址填什么啊？

### ISSUE THREAD

**Issue by ghost** [getmoneynote/moneynote-api#36]

**Comment by db-root** [comment]
有人回答吗

**Comment by icewolf-li** [comment]
比如说我在本地电脑上面搭建，ip:192.168.1.10,端口9092
那么手机上在同一局域网下，输入的就是
http://192.168.1.10:9092
必须要手动填写http，不然正则不通过

**Comment by db-root** [comment]
> 比如说我在本地电脑上面搭建，ip:192.168.1.10,端口9092 那么手机上在同一局域网下，输入的就是 http://192.168.1.10:9092 必须要手动填写http，不然正则不通过

一样的，尝试过了

![Image](https://github.com/user-attachments/assets/fb22aec1-0e1e-428d-bd29-7f4be16b59e4)
无论公网还是内网，还是什么协议，都是同样的报错

![Image](https://github.com/user-attachments/assets/56bee4bb-38d8-43b9-ab1c-15ea3be03836)
并且确认在容器内，是可以访问和连接到我前台的地址的

**Comment by icewolf-li** [comment]
挺好奇你的，前端可以访问，就是app不行对吧？
那么这直接查看手机和服务器之间的连接问题
---- 回复的原邮件 ----
***@***.***>发送日期2025年2月10日 ***@***.***>***@***.***>,
***@***.***>主题Re: [getmoneynote/moneynote-api] 后台地址填什么啊？ (Issue #36)
比如说我在本地电脑上面搭建，ip:192.168.1.10,端口9092 那么手机上在同一局域网下，输入的就是 http://192.168.1.10:9092 必须要手动填写http，不然正则不通过
一样的，尝试过了
image.png (view on web)
无论公网还是内网，还是什么协议，都是同样的报错
image.png (view on web)
并且确认在容器内，是可以访问和连接到我前台的地址的

**Comment by db-root** [comment]
> 挺好奇你的，前端可以访问，就是app不行对吧？ 那么这直接查看手机和服务器之间的连接问题
不应该是网络问题，因为同样的网络环境，访问PC地址是可以的，也就是H5地址不行

**Comment by icewolf-li** [comment]
@db-root 
我有一个想法
就是docker是把前端，api一起打包了对吧

**Comment by icewolf-li** [comment]
@db-root 
然后你看看你是不是api的端口没有开放出来，只开放了前端

**Comment by db-root** [comment]
> [@db-root](https://github.com/db-root) 然后你看看你是不是api的端口没有开放出来，只开放了前端
我是使用的这个一键部署，不确定是否有开放端口，docker-compose如下

![Image](https://github.com/user-attachments/assets/3a377cc8-759a-47c4-8279-397316460df3)
我理解这个9092是API地址，9092映射出来的10191是可以访问的

![Image](https://github.com/user-attachments/assets/0fe279cb-3830-4eac-8b13-5320969c5c9d)
这三个端口都可以访问，就是H5的这个页面访问登录遇到报错的

下列是容器中的报错日志
2025-02-10T12:47:25.848Z ERROR 23 --- [nio-9092-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: cn.biq.mn.exception.FailureMessageException: user.authentication.empty] with root cause

cn.biq.mn.exception.FailureMessageException: user.authentication.empty
        at cn.biq.mn.interceptor.AuthInterceptor.preHandle(AuthInterceptor.java:39) ~[!/:na]
        at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:146) ~[spring-webmvc-6.1.2.jar!/:6.1.2]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1084) ~[spring-webmvc-6.1.2.jar!/:6.1.2]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.1.2.jar!/:6.1.2]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.1.2.jar!/:6.1.2]
        at org.springframework.web.servlet.FrameworkServlet.doOptions(FrameworkServlet.java:950) ~[spring-webmvc-6.1.2.jar!/:6.1.2]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:599) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.1.2.jar!/:6.1.2]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.1.2.jar!/:6.1.2]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.2.jar!/:6.1.2]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.1.2.jar!/:6.1.2]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.2.jar!/:6.1.2]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.1.2.jar!/:6.1.2]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.2.jar!/:6.1.2]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]

2025-02-10T12:47:25.850Z ERROR 23 --- [nio-9092-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] threw exception

cn.biq.mn.exception.FailureMessageException: user.authentication.empty
        at cn.biq.mn.interceptor.AuthInterceptor.preHandle(AuthInterceptor.java:39) ~[!/:na]
        at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:146) ~[spring-webmvc-6.1.2.jar!/:6.1.2]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1084) ~[spring-webmvc-6.1.2.jar!/:6.1.2]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.1.2.jar!/:6.1.2]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.1.2.jar!/:6.1.2]
        at org.springframework.web.servlet.FrameworkServlet.doOptions(FrameworkServlet.java:950) ~[spring-webmvc-6.1.2.jar!/:6.1.2]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:599) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.1.2.jar!/:6.1.2]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.1.2.jar!/:6.1.2]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.2.jar!/:6.1.2]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) ~[spring-web-6.1.2.jar!/:6.1.2]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) ~[spring-web-6.1.2.jar!/:6.1.2]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:642) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:410) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:340) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:277) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:362) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:222) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:308) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:149) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]

2025-02-10T12:47:25.851Z ERROR 23 --- [nio-9092-exec-9] o.a.c.c.C.[Tomcat].[localhost]           : Exception Processing ErrorPage[errorCode=0, location=/api/v1/error]

jakarta.servlet.ServletException: Request processing failed: cn.biq.mn.exception.FailureMessageException: user.authentication.empty
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1022) ~[spring-webmvc-6.1.2.jar!/:6.1.2]
        at org.springframework.web.servlet.FrameworkServlet.doOptions(FrameworkServlet.java:950) ~[spring-webmvc-6.1.2.jar!/:6.1.2]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:599) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.1.2.jar!/:6.1.2]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.1.2.jar!/:6.1.2]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.2.jar!/:6.1.2]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) ~[spring-web-6.1.2.jar!/:6.1.2]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) ~[spring-web-6.1.2.jar!/:6.1.2]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:642) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:410) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:340) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:277) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:362) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:222) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:308) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:149) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.17.jar!/:na]
        at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
Caused by: cn.biq.mn.exception.FailureMessageException: user.authentication.empty
        at cn.biq.mn.interceptor.AuthInterceptor.preHandle(AuthInterceptor.java:39) ~[!/:na]
        at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:146) ~[spring-webmvc-6.1.2.jar!/:6.1.2]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1084) ~[spring-webmvc-6.1.2.jar!/:6.1.2]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.1.2.jar!/:6.1.2]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.1.2.jar!/:6.1.2]
        ... 36 common frames omitted

**Comment by icewolf-li** [comment]
@db-root 
user.authentication.empty

我发现基本上都是这个错误，也就是用户的令牌为空，然后我发现个问题，你发的这两张图片

![Image](https://github.com/user-attachments/assets/2f17e3cf-662e-4293-b549-8a287a4415e0)
![Image](https://github.com/user-attachments/assets/20bcdb17-1d75-42fa-9191-1dbd1f82d097)

81和82我不知道是什么服务的，但是api是9092，你映射出来也就是10191，那么app也应该访问10191，你访问81（也就是10192）端口干嘛？？

**Comment by icewolf-li** [comment]
@db-root 
噢，对，81是http的前端
82是https的前端

**Comment by db-root** [comment]
> [@db-root](https://github.com/db-root) 噢，对，81是http的前端 82是https的前端

不是吧，我访问下来发现9092是个API，81是PC、82是H5，也就是移动端页面，我现在遇到的就是82这个移动端无法登录，访问都是正常的

**Comment by db-root** [comment]
我也不确定这么理解是否正确，还得大佬帮忙看下

**Comment by icewolf-li** [comment]
> > [@db-root](https://github.com/db-root) 噢，对，81是http的前端 82是https的前端
> 
> 不是吧，我访问下来发现9092是个API，81是PC、82是H5，也就是移动端页面，我现在遇到的就是82这个移动端无法登录，访问都是正常的

具体的81和82我不知道，但是我看你截图的前端81有个“不安全”，也就是说是http协议，82我不知道，但是docker底层逻辑肯定是容器内部前端访问的api是9092，而你的app也应该访问9092（映射也就是10191），你要这么理解，前后端分离，前端（网页版==h5==app），后端（api）

**Comment by db-root** [comment]
我降低了浏览器加载速率，发现提交登录的时候第一次提示登录成功，后又出现报错

![Image](https://github.com/user-attachments/assets/96907840-e4a4-4264-bac5-ba7a48421ac1)

![Image](https://github.com/user-attachments/assets/84dfbb7c-1bd1-43c8-a5e2-e5dc1e88da79)

![Image](https://github.com/user-attachments/assets/de78c33a-2271-424e-93f5-06eda99c5bad)
你看下，这个站点地址不管是写API的10191还是前端的10192都是一样的，先提示的登录成功，再出现的报错

**Comment by icewolf-li** [comment]
我看的有一点迷糊，我捋一下思路
你的服务器ip：192.168.191.5
然后docker端口映射：10191-9092         10192-81       10193-82
手机同一局域网

电脑能访问服务器的 前端（10192）、后端（10191）
然后现在是手机上的app无法访问到后端api（10191）
对吗

**Comment by icewolf-li** [comment]
@db-root 
![Image](https://github.com/user-attachments/assets/b4232a3f-ea5e-4803-94c6-9af5c14918d5) 
手机浏览器，还是手机app

**Comment by db-root** [comment]
> [@db-root](https://github.com/db-root) ![Image](https://github.com/user-attachments/assets/b4232a3f-ea5e-4803-94c6-9af5c14918d5) 手机浏览器，还是手机app

使用的浏览器，没有手机APP

**Comment by db-root** [comment]
> 我看的有一点迷糊，我捋一下思路 你的服务器ip：192.168.191.5 然后docker端口映射：10191-9092 10192-81 10193-82 手机同一局域网
> 
> 电脑能访问服务器的 前端（10192）、后端（10191） 然后现在是手机上的app无法访问到后端api（10191） 对吗

后端也是可以访问，这三个端口都可以访问，但是访问H5地址，也就是10193-82，因为IOS系统无法安装APP官方教程说是访问手机端网站，也就是这个10193端口

**Comment by db-root** [comment]
访问10193-82这个地址是可以访问没有问题，但登录的时候无法登录

**Comment by icewolf-li** [comment]
> 访问10193-82这个地址是可以访问没有问题，但登录的时候无法登录

方便远程么todesk？
我有好几个疑惑点，首先是你用的是docker-compose-ali-no-mysql.yml，自己有了数据库，然后我看他其实映射出来的都是80端口，也就是web版（pc版），也都是在配置文件中写死了docker容器内api地址，
按道理来说：无论是哪个访问的都应该是web版，有点好奇，想远程看看，方便的话我发个邮箱，你联系我

**Comment by db-root** [comment]
> > 访问10193-82这个地址是可以访问没有问题，但登录的时候无法登录
> 
> 方便远程么todesk？ 我有好几个疑惑点，首先是你用的是docker-compose-ali-no-mysql.yml，自己有了数据库，然后我看他其实映射出来的都是80端口，也就是web版（pc版），也都是在配置文件中写死了docker容器内api地址， 按道理来说：无论是哪个访问的都应该是web版，有点好奇，想远程看看，方便的话我发个邮箱，你联系我

可以的，不过我这几天都是晚班12点下班，你看你什么时候方便，可以添加一个联系方式，我微信：zb839795977

**Comment by citizen-zhangjz** [comment]
出了一样的问题，我使用了k8s部署成功，web端可以正常访问。 就是这个手机网页版，登录成功后就报错。

![Image](https://github.com/user-attachments/assets/123c05d1-7deb-4f22-a647-2c8cf93f891d)

Q群申请了，无人审核
端口映射
80:30811/TCP,9092:30812/TCP,81:30813/TCP,82:30814/TCP

 [root@node1 ~]# kubectl get svc -owide
NAME                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                 AGE   SELECTOR
cash-note-svc         NodePort    10.96.173.36    <none>        80:30811/TCP,9092:30812/TCP,81:30813/TCP,82:30814/TCP   71m   app=cash-note
mysql-svc             NodePort    10.96.243.78    <none>        3306:32349/TCP                                          12d   app=mysql

**Comment by icewolf-li** [comment]
> 出了一样的问题，我使用了k8s部署成功，web端可以正常访问。 就是这个手机网页版，登录成功后就报错。
> 
> ![Image](https://github.com/user-attachments/assets/123c05d1-7deb-4f22-a647-2c8cf93f891d)
> 
> Q群申请了，无人审核

我没有仔细查看那个镜像，但我目前排查出的问题就是前端页面的问题，我只是一个业余的爱好者，q群啥的作者应该也不管了，我目前主要中心在研究api，然后app端我自己开发，作者没有提供ios的app，但是可以自己从flutter构建出来

**Comment by icewolf-li** [comment]
我目前没有时间去修这个bug，我也不是这个项目的开发者，但是这个项目的后端api挺和我心意，我学习这个开源项目并打算自己写一个好看的前端，目前大致了解完api，并且“优化”成我熟悉的技术栈，目前安卓app能正常使用

前端页面大概没那么快，最近比较忙，目前是先开发网页版（兼容手机端）-》安卓/ios
